name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install EB CLI using pip
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    
    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy
