name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
      
    steps:
    - uses: actions/checkout@v4

    - name: Install EB CLI using pip
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy
