name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::730335453782:oidc-provider/token.actions.githubusercontent.com

    - name: Install EB CLI using pip
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli

    
    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy
