name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install EB CLI
      run: |
        sudo apt update
        sudo apt install awscli

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        eb deploy
