name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Install EB CLI
      run: |
        sudo apt update
        sudo apt install awsebcli

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        eb deploy
